export const ProductsArray = [
    {
      id: '1',
      name: 'Product 1',
      price: 100,
      image: 'product1.jpg',
      listingDate: '2024-01-01',
      description: 'Description 1',
      itemType: 'Type 1',
      marketCategories: ['Category 1', 'Category 2'],
    },
    {
      id: '2',
      name: 'Product 2',
      price: 200,
      image: 'product2.jpg',
      listingDate: '2024-01-02',
      description: 'Description 2',
      itemType: 'Type 2',
      marketCategories: ['Category 2', 'Category 3'],
    },
    {
      id: '3',
      name: 'Product 3',
      price: 300,
      image: 'product3.jpg',
      listingDate: '2024-01-03',
      description: 'Description 3',
      itemType: 'Type 3',
      marketCategories: ['Category 3', 'Category 4'],
    },
    {
      id: '4',
      name: 'Product 4',
      price: 400,
      image: 'product4.jpg',
      listingDate: '2024-01-04',
      description: 'Description 4',
      itemType: 'Type 4',
      marketCategories: ['Category 4', 'Category 5'],
    },
    {
      id: '5',
      name: 'Product 5',
      price: 500,
      image: 'product5.jpg',
      listingDate: '2024-01-05',
      description: 'Description 5',
      itemType: 'Type 5',
      marketCategories: ['Category 5', 'Category 6'],
    },
    {
      id: '6',
      name: 'Product 6',
      price: 600,
      image: 'product6.jpg',
      listingDate: '2024-01-06',
      description: 'Description 6',
      itemType: 'Type 6',
      marketCategories: ['Category 6', 'Category 7'],
    },
    {
      id: '7',
      name: 'Product 7',
      price: 700,
      image: 'product7.jpg',
      listingDate: '2024-01-07',
      description: 'Description 7',
      itemType: 'Type 7',
      marketCategories: ['Category 7', 'Category 8'],
    },
    // Add your product data here
  ]